import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/header.view"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Traceable Ledger System",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <div className="relative flex min-h-screen flex-col bg-background">
                    <main className="px-8 py-2">{children}</main>
                </div>
            </body>
        </html>
    )
}
